Remove reflection-based DualWielding implementation, and update related utilities
zDevelopers/QuartzLib pull request #70
Opened 2020-12-16 02:10 UTC by prokopyl

This PR does the following:

- Remove the `DualWielding` reflection-based utility class since all methods are now in Bukkit (as discussed in #43)
- Move the still useful `DualWielding.getHoldingHand()` method to `InventoryUtils`
- Also move the `ItemUtils.breakItemInHand()` methods to `InventoryUtils`, as they are more related to inventories than items
- Move the `DualWielding` enum to `InventoryUtils`, now as a simple enum representing the hands
- Change `ItemUtils.consumeItem()` to `ItemUtils.consumeItemInMainHand` and `ItemUtils.consumeItemInOffHand` (as discussed in #41)
- Rename `ItemUtils.damageItemInHand()` to `ItemUtils.damageItem()`, and update it to use the `Damageable` API (see #42)

This fixes #41, #42 and #43.

2020-12-26 11:50 UTC, AmauryCarrade requested changes
Nice changes! Only thing: missing changelog update. At least:

- added `ItemUtils.consumeItemInOffHand`;
- moved `ItemUtils.consumeItem` to `ItemUtils.consumeItemInMainHand`;
- moved `ItemUtils.damageItemInHand` to `ItemUtils.damageItem`;
- `ItemUtils.damageItem` now returns `true` if the damaged item was broken;
- moved `ItemUtils.breakItemInHand` methods to `InventoryUtils.breakItemInHand`;
- moved `DualWielding` to `InventoryUtils.DualWielding`;
- moved `DualWieldling` methods to `InventoryUtils`;
- removed `DualWieldling.setItemInHand` and `DualWieldling.getItemInHand` (use Bukkit API for that).

2020-12-26 11:50 UTC, AmauryCarrade commented on src/main/java/fr/zcraft/quartzlib/tools/items/InventoryUtils.java
> +        //player.playSound(player.getLocation(), Sound.ITEM_BREAK, 0.8f, 1);
As we are only 1.15+, we could bring back sounds! Maybe in another PR, dunno.

2021-04-11 17:37 UTC, Vlammar approved these changes

2021-04-11 18:34 UTC, AmauryCarrade approved these changes

2021-04-11 18:34 UTC, merged